export interface ApprovedMedicine {
  id: string;
  name: string;
  company: string;
  category: "Capsule" | "Tablet" | "Injection" | "Syrup" | "Ointment" | "Drops";
  batchNumber: string;
  price: number;
  approvedBy: string;
  approvedDate: string;
  expiryDate: string;
  manufacturingDate: string;
  mrp: number;
  licenseNumber: string;
  composition: string;
  dosage: string;
  description: string;
  image?: string;
  status: "approved";
}

export const initialApprovedMedicines: ApprovedMedicine[] = [
  {
    id: "app-1",
    name: "Lipitor 20mg",
    company: "Pfizer Inc.",
    category: "Tablet",
    batchNumber: "MED-20984",
    price: 340,
    approvedBy: "Admin User",
    approvedDate: "20 July 2026",
    expiryDate: "15 Aug 2028",
    manufacturingDate: "01 Sep 2025",
    mrp: 340,
    licenseNumber: "DL-PFZ-99881",
    composition: "Atorvastatin Calcium Trihydrate 20mg",
    dosage: "One tablet daily at bedtime",
    description: "Lipitor (atorvastatin) belongs to a group of drugs called statins. It is used to lower cholesterol and triglycerides (types of fat) in the blood, and to slow the buildup of plaque in blood vessels.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-2",
    name: "Amoxil 500mg",
    company: "GlaxoSmithKline",
    category: "Capsule",
    batchNumber: "MED-11043",
    price: 180,
    approvedBy: "Super Admin",
    approvedDate: "18 July 2026",
    expiryDate: "30 Jun 2028",
    manufacturingDate: "05 Jul 2025",
    mrp: 180,
    licenseNumber: "DL-GSK-32112",
    composition: "Amoxicillin Trihydrate equivalent to 500mg Amoxicillin",
    dosage: "Three times a day after meals, or as prescribed by a physician",
    description: "Amoxil is a penicillin antibiotic that fights bacteria. It is used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-3",
    name: "Insulin Humalog 100 U/ml",
    company: "Eli Lilly & Co.",
    category: "Injection",
    batchNumber: "MED-77643",
    price: 1250,
    approvedBy: "Admin User",
    approvedDate: "15 July 2026",
    expiryDate: "12 Dec 2027",
    manufacturingDate: "10 Dec 2024",
    mrp: 1250,
    licenseNumber: "DL-LLY-55442",
    composition: "Insulin Lispro 100 Units/ml",
    dosage: "Subcutaneous injection within 15 minutes before a meal, dosage as titrated",
    description: "Humalog is a fast-acting insulin that starts to work about 15 minutes after injection, peaks in about 1 hour, and keeps working for 2 to 4 hours. It is used to improve blood sugar control in adults and children with diabetes mellitus.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-4",
    name: "Benadryl Cough Syrup",
    company: "Johnson & Johnson",
    category: "Syrup",
    batchNumber: "MED-33421",
    price: 110,
    approvedBy: "Admin User",
    approvedDate: "12 July 2026",
    expiryDate: "28 Feb 2028",
    manufacturingDate: "01 Mar 2025",
    mrp: 110,
    licenseNumber: "DL-JNJ-45672",
    composition: "Diphenhydramine HCl 12.5mg, Ammonium Chloride 125mg, Sodium Citrate 57mg per 5ml",
    dosage: "10ml every 4 hours, not to exceed 6 doses in 24 hours",
    description: "Benadryl Cough Formula provides symptomatic relief from allergy symptoms, congestion, and irritating dry cough. Formulated with antihistamines and expectorants to ease throat itchiness and chest congestion.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-5",
    name: "Betadine Ointment 10%",
    company: "Mundipharma",
    category: "Ointment",
    batchNumber: "MED-88902",
    price: 95,
    approvedBy: "Super Admin",
    approvedDate: "10 July 2026",
    expiryDate: "30 Sep 2028",
    manufacturingDate: "01 Oct 2025",
    mrp: 95,
    licenseNumber: "DL-MUN-65431",
    composition: "Povidone-Iodine IP 10% w/w (available Iodine 1% w/w)",
    dosage: "Apply locally to the affected area 1-3 times daily, or as directed",
    description: "Betadine antiseptic cream/ointment is a water-soluble topical microbicide. It is used for the treatment of minor cuts, abrasions, burns, and surgical wounds, preventing infections caused by bacteria, fungi, and viruses.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-6",
    name: "Otrivin Pediatric 0.05%",
    company: "Novartis AG",
    category: "Drops",
    batchNumber: "MED-11234",
    price: 65,
    approvedBy: "Admin User",
    approvedDate: "08 July 2026",
    expiryDate: "30 Apr 2028",
    manufacturingDate: "01 May 2025",
    mrp: 65,
    licenseNumber: "DL-NVS-78912",
    composition: "Xylometazoline Hydrochloride 0.05% w/v in aqueous buffered vehicle",
    dosage: "1-2 drops in each nostril, 1-2 times daily. Do not exceed 3 applications per day.",
    description: "Otrivin Pediatric nasal drops contain Xylometazoline, a vasoconstrictor that clears nasal passages by reducing swelling of mucosa. Especially formulated for infants and children for fast relief from blocked nose.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-7",
    name: "Augmentin 625 DUO",
    company: "GlaxoSmithKline",
    category: "Tablet",
    batchNumber: "MED-55412",
    price: 220,
    approvedBy: "Super Admin",
    approvedDate: "05 July 2026",
    expiryDate: "31 Oct 2027",
    manufacturingDate: "12 Oct 2024",
    mrp: 220,
    licenseNumber: "DL-GSK-32112",
    composition: "Amoxicillin Trihydrate 500mg, Potassium Clavulanate Diluted equivalent to Clavulanic Acid 125mg",
    dosage: "One tablet twice daily, or as advised by a doctor",
    description: "Augmentin 625 Duo is an oral antibacterial combination consisting of the broad-spectrum antibiotic amoxicillin and the beta-lactamase inhibitor clavulanic acid, preventing bacteria from destroying amoxicillin.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-8",
    name: "Panadol 500mg",
    company: "Haleon plc",
    category: "Tablet",
    batchNumber: "MED-99042",
    price: 30,
    approvedBy: "Admin User",
    approvedDate: "02 July 2026",
    expiryDate: "30 Nov 2029",
    manufacturingDate: "01 Dec 2024",
    mrp: 30,
    licenseNumber: "DL-HAL-12499",
    composition: "Paracetamol BP 500mg",
    dosage: "1-2 tablets every 4-6 hours as required, max 8 tablets in 24 hours",
    description: "Panadol tablets provide fast and effective relief of temporary pain and discomfort associated with headaches, muscle aches, period pain, toothache, and cold/flu symptoms. Gentle on sensitive stomachs.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-9",
    name: "Ventolin Inhaler 100mcg",
    company: "GlaxoSmithKline",
    category: "Injection", // Closest category is Injection, but we'll categorize it appropriately
    batchNumber: "MED-78891",
    price: 150,
    approvedBy: "Admin User",
    approvedDate: "28 June 2026",
    expiryDate: "31 Jan 2028",
    manufacturingDate: "15 Jan 2025",
    mrp: 150,
    licenseNumber: "DL-GSK-32112",
    composition: "Salbutamol Sulfate equivalent to Salbutamol 100mcg per actuation",
    dosage: "1 or 2 inhalations (actuations) for acute asthma spasms, max 8 inhalations/day",
    description: "Ventolin CFC-free inhaler contains salbutamol, a bronchodilator. It acts directly on muscles in the airways, causing them to relax and dilating the air passages, helping asthmatics breathe easier.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-10",
    name: "Zantac 150mg",
    company: "Sanofi",
    category: "Tablet",
    batchNumber: "MED-44563",
    price: 120,
    approvedBy: "Super Admin",
    approvedDate: "25 June 2026",
    expiryDate: "15 Jul 2028",
    manufacturingDate: "20 Jul 2025",
    mrp: 120,
    licenseNumber: "DL-SNF-88992",
    composition: "Ranitidine Hydrochloride equivalent to Ranitidine 150mg",
    dosage: "One tablet twice daily (morning and evening), or as directed",
    description: "Zantac (ranitidine) is an H2 blocker. It works by reducing the amount of acid your stomach produces. It is used to treat and prevent ulcers in the stomach and intestines, GERD, and hypersecretory conditions.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-11",
    name: "Neurobion Forte",
    company: "Merck Group",
    category: "Tablet",
    batchNumber: "MED-23341",
    price: 55,
    approvedBy: "Admin User",
    approvedDate: "22 June 2026",
    expiryDate: "30 Sep 2028",
    manufacturingDate: "01 Oct 2025",
    mrp: 55,
    licenseNumber: "DL-MRK-77112",
    composition: "Thiamine Mononitrate (Vit B1) 10mg, Riboflavin (Vit B2) 10mg, Pyridoxine HCl (Vit B6) 3mg, Cyanocobalamin (Vit B12) 15mcg, Nicotinamide 45mg, Calcium Pantothenate 50mg",
    dosage: "1 tablet daily or as directed by doctor",
    description: "Neurobion Forte is a combination of B vitamins that are essential for healthy nerves, red blood cells, and protein metabolism. Commonly used for treating vitamin deficiencies and neuropathic pain.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-12",
    name: "Clexane 40mg/0.4ml",
    company: "Sanofi",
    category: "Injection",
    batchNumber: "MED-90812",
    price: 490,
    approvedBy: "Super Admin",
    approvedDate: "20 June 2026",
    expiryDate: "31 Mar 2028",
    manufacturingDate: "01 Apr 2025",
    mrp: 490,
    licenseNumber: "DL-SNF-88992",
    composition: "Enoxaparin Sodium 40mg/0.4ml aqueous solution for injection",
    dosage: "Subcutaneous injection as directed. Do not administer intramuscularly.",
    description: "Clexane is a low molecular weight heparin (LMWH). It is an anticoagulant medication used to treat and prevent deep vein thrombosis (DVT) and pulmonary embolism, especially during pregnancy or high-risk surgeries.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-13",
    name: "Dextrose 5% saline",
    company: "Baxter International",
    category: "Injection",
    batchNumber: "MED-88123",
    price: 85,
    approvedBy: "Admin User",
    approvedDate: "15 June 2026",
    expiryDate: "30 May 2028",
    manufacturingDate: "01 Jun 2025",
    mrp: 85,
    licenseNumber: "DL-BAX-44331",
    composition: "Dextrose Hydrous 5.0g, Sodium Chloride 0.9g per 100ml",
    dosage: "Intravenous infusion, rate adjusted as per fluid balance requirement",
    description: "Baxter Dextrose 5% in Normal Saline is a sterile, non-pyrogenic IV solution designed for fluid replenishment, calorie supply, and electrolyte normalization. Indicated for hydration therapy.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-14",
    name: "Gelusil Antacid Liquid",
    company: "Pfizer Inc.",
    category: "Syrup",
    batchNumber: "MED-66120",
    price: 130,
    approvedBy: "Admin User",
    approvedDate: "10 June 2026",
    expiryDate: "31 Aug 2028",
    manufacturingDate: "01 Sep 2025",
    mrp: 130,
    licenseNumber: "DL-PFZ-99881",
    composition: "Aluminium Hydroxide Gel 250mg, Magnesium Hydroxide 250mg, Activated Dimethicone 50mg per 5ml",
    dosage: "5-10ml between meals and at bedtime, or as directed by physician",
    description: "Gelusil is a trusted antacid-antiflatulent liquid that provides quick relief from acidity, heartburn, gas, and stomach discomfort. Works by neutralizing gastric acid and breaking up gas bubbles.",
    image: "/medicine-placeholder.png",
    status: "approved"
  },
  {
    id: "app-15",
    name: "Corex DX Syrup",
    company: "Pfizer Inc.",
    category: "Syrup",
    batchNumber: "MED-55099",
    price: 145,
    approvedBy: "Super Admin",
    approvedDate: "08 June 2026",
    expiryDate: "31 Jul 2028",
    manufacturingDate: "15 Aug 2025",
    mrp: 145,
    licenseNumber: "DL-PFZ-99881",
    composition: "Dextromethorphan Hydrobromide 10mg, Chlorpheniramine Maleate 4mg per 5ml",
    dosage: "5ml twice daily or as directed by a healthcare professional",
    description: "Corex DX is a combination medication containing an antihistamine and a cough suppressant. It is used to treat dry cough, sneezing, and runny nose caused by allergies, common cold, or respiratory infections.",
    image: "/medicine-placeholder.png",
    status: "approved"
  }
];
